[package]
name = "periscope"
version = "0.1.0"
edition = "2021"
author = "Nadir Fejzic <nadirfejzo@gmail.com>"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
